### ISSUE TITLE
[BUG] Can't preview accent on dressing room url

### ISSUE THREAD

**Issue by JavaMeana** [Nensec/FRSkinTester#23]
When trying to preview my accent SpiritOfKalang, I can't seem to get a preview on this dressing room link:
https://www1.flightrising.com/dgen/dressing-room/dragon?did=72163803&skin=0&apparel=29582,21832,33816,9452,35549,35536,44227&xt=dressing.png

I used this existing dragon:
https://www1.flightrising.com/dragon/72163803

With this outfit:
https://www1.flightrising.com/dressing/outfit/1909230

The resulting screen just shows the base dragon without the outfit applied.

**Comment by Nensec** [comment]
@JavaMeana This is due to caching, one of my many pains to keep traffic to FR as low as possible. If you look on the preview result page there is a blue alert under the images that says it is a cached version. At the end there is a clickable link that will clear the cache and it will then re-generate the preview with the new info.

![image](https://user-images.githubusercontent.com/672037/162626757-8fdf2b8f-0453-44c8-b23e-c73a65aebf81.png)

![image](https://user-images.githubusercontent.com/672037/162626784-970529fe-4362-4bd3-be8c-c107f5dbc553.png)

In this case what happened was you previewed it on a real dragon which had something equipped, so I generated both the dragon and apparel previews. Then when you used the dressing room preview I checked to see if there were already cached images for that dragon and both the base dragon and apparel image existed, thus returning them right away without doing any further processing.

To prevent having dozens of images saved for each dragon whenever someone changes their apparel, I opted to put the burden of clearing the cache to the user by letting them forcibly regenerate the image.

**Comment by JavaMeana** [comment]
I see! How odd, I pressed the link in the blue window but just got the same
result back, could it be an issue on my end? No matter how many times I
clicked the reload, I just got the same images BUT when I tried previewing
later on, it did work normally again. What I did differently however is at
first I was previewing with the link from my manage skins and the second
time I used the link through normal skin browsing but I doubt that would
have caused the issue.

**Comment by Nensec** [comment]
They should result in the same link anyway. I am guessing your browser is caching the images (which it should). I don't know if I can force a browser to download the new images and cache those instead of the original ones. Normally speaking a browser won't even attempt to get a newer version if it is already cached, so I don't have much control over it : /

**Comment by JavaMeana** [comment]
No worries at all! I now know where the issue lies so I can know what to do
in the future ty! Have a great rest of your day!
