### ISSUE TITLE
[Feature request] Delete previews

### ISSUE THREAD

**Issue by Akaineko-astasi** [Nensec/FRSkinTester#8]
The number of previews grows fast, and we don't really need all of them after seeing them the first time. Honestly I thought the site would not store previews at all and only stores skins, when I found it xD So I propose using lesser disc and interface space and delete unused things.

**Description of the feature**
User may delete the preview image generated. 
Personally I'd prefer a small bootstrap-like X in the top right corner of the button that leads to the particular preview.
The config "confirm before deleting" would be also good, set to true by default, which would result in the confirmation window like "Are you sure? This will delete the image forever." after clicking the X, and in no confirmation windows for deleters like me when set to false.

**Contextual information**
I'm a skin buyer, no artist. I use the tool in two cases: 
* previewing skins-to-be-printed I don't really know if I like or not;
* previeving pretty skins-to-pe-printed on pretty dragons, when I like the combo. 

In the first case, I never use the preview again.
In the second case, I enjoy the look in dragon's bio and once the skin is printed I replace the raw image with a FR skin preview with the tag `[skin=ID]`.

Currently my Generated previews page looks like this:
![image](https://user-images.githubusercontent.com/12430338/54914624-70a88080-4f06-11e9-9177-2dc64495a15f.png)
And the first two are useless.

I used the tool for 2 skins for now. I anticipate there would be around 6 images total when I use the tool again, and more than 50% of the images would never be referred to. It's 0.5 images for each skin that I use afterwards, so far.

**Comment by Nensec** [comment]
It has crossed my mind to be able to delete previews, but ultimately (at least for now) I decided against it. The process of how it came to be like this is features building on top of eachother.

Initially previews were not tied to accounts, they were just tied to the skin in the database for statistical purposes. Later I made them viewable by the skin creator so they can have insight in what their skin was being put on. Now that profiles are a thing those previews are linked to accounts if one is logged in while making the preview, or anonymous and unlinked if not. The vast majority (98.47%) of previews generated are currently not linked to accounts. Of course this partially due to logging in being optional, quite recent and not really encouraged for buyers.

On a separate note: If an image is linked anywhere and then deleted you get an ugly "image not found" icon in forums and whatnot.

However, I would like to ask for a change in your feature request:
Instead of deleting the preview, I could make it so a preview can be orphaned (removing the link to one's account) or allowing it to be hidden from your public profile.

**Comment by Akaineko-astasi** [comment]
> Initially previews were not tied to accounts, they were just tied to the skin in the database for statistical purposes. Later I made them viewable by the skin creator so they can have insight in what their skin was being put on. 

Ah, that makes a lot of sence now, I didn't mean to alter history or to hide things from skin creators.

>The vast majority (98.47%) of previews generated are currently not linked to accounts. Of course this partially due to logging in being optional, quite recent and not really encouraged for buyers.

Aha. I see.
> On a separate note: If an image is linked anywhere and then deleted you get an ugly "image not found" icon in forums and whatnot.

You're right, I suppose we don't want to make checks if an image is linked anywhere befor deleting.

> Instead of deleting the preview, I could make it so a preview can be orphaned (removing the link to one's account) or allowing it to be hidden from your public profile.

Considering other thoughts orphaning would be good, but do the skin creator's statistic include any info of who did the preview? If it does, simple hiding a preview from user's sight in the Previews Generated box would be the best, as I don't really mean to hide that info from the skin creators. If not, orphaning would be the best. 

Thanks! <3

**Comment by Nensec** [comment]
No, skin creators only see if a preview was made on a real or a scry (much the same as you would on your own profile). If you were to know how FR works a little you can figure out based on the image URL who owns the dragon however.

I am leaning towards allowing to orphan a preview myself, since it essentially covers the reasoning why you would want it off your profile (remove clutter) and keeps the record for the skin creator's stats.

I'm currently working on a side-project, so this will probably be done a bit later.

Thanks for the request however, I am glad people are open to suggest changes :D

**Comment by Nensec** [comment]
You should now be able to remove previews from your profile when you view your own profile ( https://frskintester.nensec.com/profile )

I've not added a setting for asking the question, as I plan to refactor settings in the near future
